sudo: false
language: node_js
node_js:
  # - "0.10"
  # - "0.12"
  - "4"
  - "6"
  - "8"
  - "9"
  - "10"

os:
  - linux
  - osx

matrix:
    allow_failures:
    - node_js: "4"


before_script:
  - npm install -g istanbul
  - npm install coveralls
  - npm install -g mocha
  - npm install -g browserify 
  - npm install -g uglify-js
  - npm install -g codeclimate-test-reporter
  - npm install -g mocha-phantomjs object-assign
  - npm install

after_success:
  - make coveralls
script:
  - npm test
  - make test-cov
